primary
    = INT
    | FLOAT
    | STRING
    | "true"
    | "false"
    | "(", expression, ")";

index
    = primary, { "[", expression, "]" };

suffix
    = suffix, ( "?"
    | "!" )
    | primary;

prefix
    = ( "!"
    | "-" ), prefix
    | primary;

factor
    = prefix, { ( "/"
    | "*" ), prefix };

term
    = factor, { ( "-"
    | "+" ), factor };

comparison
    = term, { ( ">"
    | ">="
    | "<"
    | "<=" ), term };

equality
    = comparison, { ( "!="
    | "==" ), comparison };

expression
    = equality, { ( "&&"
    | "||" ), equality };