package tokens

var Runes = map[rune]Type{
	'(': LParen,
	')': RParen,
	'*': Asterisk,
	'+': Plus,
	',': Comma,
	'-': Minus,
	'.': Dot,
	'/': Divide,
	':': Colon,
	'<': LT,
	'=': Assign,
	'>': GT,
	'?': Question,
	'@': Builtin,
	'[': LBracket,
	']': RBracket,
	'{': LBrace,
	'}': RBrace,
	'!': Not,
	'~': Tilde,
	'|': Pipe,
	'&': BitAnd,
	'^': BitXor,
}

var Keywords = map[string]Type{
	Any.String():        Any,
	ASCII.String():      ASCII,
	Async.String():      Async,
	Bool.String():       Bool,
	Break.String():      Break,
	Case.String():       Case,
	Comparable.String(): Comparable,
	Complex32.String():  Complex32,
	Complex64.String():  Complex64,
	Complex128.String(): Complex128,
	Continue.String():   Continue,
	Default.String():    Default,
	Dynamic.String():    Dynamic,
	Else.String():       Else,
	Enum.String():       Enum,
	Export.String():     Export,
	Error.String():      Error,
	False.String():      False,
	Float16.String():    Float16,
	Float32.String():    Float32,
	Float64.String():    Float64,
	For.String():        For,
	Function.String():   Function,
	GoImport.String():   GoImport,
	If.String():         If,
	Import.String():     Import,
	In.String():         In,
	Int8.String():       Int8,
	Int16.String():      Int16,
	Int32.String():      Int32,
	Int64.String():      Int64,
	Int128.String():     Int128,
	Interface.String():  Interface,
	Map.String():        Map,
	Match.String():      Match,
	Number.String():     Number,
	Ordered.String():    Ordered,
	Package.String():    Package,
	Procedure.String():  Procedure,
	Return.String():     Return,
	Select.String():     Select,
	Set.String():        Set,
	Signed.String():     Signed,
	String.String():     String,
	Struct.String():     Struct,
	Summable.String():   Summable,
	Switch.String():     Switch,
	True.String():       True,
	Uint8.String():      Uint8,
	Uint16.String():     Uint16,
	Uint32.String():     Uint32,
	Uint64.String():     Uint64,
	Uint128.String():    Uint128,
	UTF8.String():       UTF8,
	Variable.String():   Variable,
}

var Types = map[Type]struct{}{
	Any:        {},
	ASCII:      {},
	Bool:       {},
	Complex32:  {},
	Complex64:  {},
	Complex128: {},
	Error:      {},
	Float16:    {},
	Float32:    {},
	Float64:    {},
	Int8:       {},
	Int16:      {},
	Int32:      {},
	Int64:      {},
	Int128:     {},
	String:     {},
	Uint8:      {},
	Uint16:     {},
	Uint32:     {},
	Uint64:     {},
	Uint128:    {},
	UTF8:       {},
}

var FuncTypes = map[Type]struct{}{
	Function:  {},
	Procedure: {},
}
